

#ifndef _STORAGE_ERROR_H
#define _STORAGE_ERROR_H

#include "base/platform.h"

SMILE_NS_BEGIN

enum class storageError_t : uint8_t {
  E_NO_ERROR = 0,
  E_INVALID_PATH,
  E_PATH_ALREADY_EXISTS,
  E_INVALID_CONFIG,
  E_STORAGE_NOT_OPEN,
  E_OUT_OF_BOUNDS_EXTENT,
  E_OUT_OF_BOUNDS_READ,
  E_OUT_OF_BOUNDS_WRITE,
  E_CRITICAL_ERROR
};

SMILE_NS_END

#endif /* ifndef _STORAGE_ERROR_H
 */
