


#ifndef _DATA_ERROR_H_
#define _DATA_ERROR_H_

#include "../base/platform.h"


SMILE_NS_BEGIN

enum class ErrorCode : uint8_t {
  E_NO_ERROR = 0,
  E_UNEXPECTED_ERROR,

  //GRAPH ERRORS
  E_GRAPH_INVALID_TYPE,
  E_GRAPH_EXISTING_TYPE,
  E_GRAPH_UNEXISTING_ATTRIBUTE_TYPE,
  E_GRAPH_EXISTING_ATTRIBUTE_TYPE,
  E_GRAPH_ATTRIBUTE_DATA_TYPE_MISSMATCH,
  E_GRAPH_ATTRIUTE_MAX_NUMBER,
  E_GRAPH_TYPE_MAX_NUMBER,
  E_GRAPH_UNEXISTING_OBJECT,

  //LOADER ERRORS
//  E_LOADER_UNEXPECTED_END_OF_STREAM,

  // STORAGE ERRORS
  E_STORAGE_INVALID_PATH,
  E_STORAGE_PATH_ALREADY_EXISTS,
  E_STORAGE_INVALID_CONFIG,
  E_STORAGE_NOT_OPEN,
  E_STORAGE_OUT_OF_BOUNDS_PAGE,
  E_STORAGE_OUT_OF_BOUNDS_READ,
  E_STORAGE_OUT_OF_BOUNDS_WRITE,
  E_STORAGE_CRITICAL_ERROR,

  // BUFFER POOL ERRORS
  E_BUFPOOL_OUT_OF_MEMORY,
  E_BUFPOOL_PAGE_NOT_PRESENT,
  E_BUFPOOL_UNABLE_TO_ACCCESS_PROTECTED_PAGE,
  E_BUFPOOL_PAGE_NOT_ALLOCATED,
  E_BUFPOOL_POOL_SIZE_NOT_MULTIPLE_OF_PAGE_SIZE,
  E_BUFPOOL_ALLOCATED_PAGE_IN_FREELIST,
  E_BUFPOOL_PROTECTED_PAGE_IN_FREELIST,
  E_BUFPOOL_FREE_PAGE_NOT_IN_FREELIST,
  E_BUFPOOL_BUFFER_DESCRIPTOR_INCORRECT_DATA,
  E_BUFPOOL_FREE_PAGE_MAPPED_TO_BUFFER,

  // SCHEMA ERRORS
  
  E_SCHEMA_PAGE_CORRUPTED,
  E_SCHEMA_ELEMENT_NAME_TOO_LONG,
  E_SCHEMA_NODE_TYPE_ALREADY_EXISTS,
  E_SCHEMA_NODE_TYPE_NOT_EXISTS

};

/** 
 * For convinience. Tells if the error is an error.
 **/
bool isError(ErrorCode e);


SMILE_NS_END


#endif /* ifndef _DATA_ERROR_H_ */
